<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>negi3000</title>
    <link rel="icon" type="image/png" href="favicon.ico">
    <link href="assets/css/preloader.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:400,400i,700,700i" rel="stylesheet">
    <link href="components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="components/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css">
    <link href="components/AdminLTE/dist/css/skins/skin-blue-light.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css/main.css" rel="stylesheet" type="text/css">
</head>
<body class="hold-transition skin-blue-light sidebar-mini app">
    <div id="app">
    </div>

    <?= $this->fetch("_components/preloader.phtml"); ?>

    <script>window.token = <?= json_encode($token) ?>;</script>
    <script src="build.js"></script>
    <script src="components/jquery/dist/jquery.min.js"></script>
    <script src="components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="components/AdminLTE/dist/js/app.min.js"></script>
    <script src="assets/js/preloader.js"></script>
    <script>$(document).ready(function() { setTimeout(function() { $(window).trigger('resize'); }, 500) });</script>
</body>
</html>
