<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>negi3000</title>
    <link rel="icon" type="image/png" href="favicon.ico">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web:400,400i,700,700i" rel="stylesheet">
    <link href="assets/css/coreui/style.css" rel="stylesheet" type="text/css">
    <link href="components/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="assets/css/main.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="app">
    </div>

    <script src="build.js"></script>
</body>
</html>
