<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>negi3000</title>
    <link rel="icon" type="image/png" href="favicon.ico">
    <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css">
    <link href="assets/css/main.css" rel="stylesheet" type="text/css">
</head>
<body class="home">
    <h1 class="site-title">negi3000</h1>
    <a href="app">open app</a>
</body>
</html>
