<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>negi3000</title>
    <base href="<?= $baseUrl ?>" />
    <link href="assets/css/preloader.css" rel="stylesheet">
    <link href="components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="components/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="components/AdminLTE/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css">
    <link href="assets/css/main.css" rel="stylesheet">
</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <b>NEGI</b>3000</a>
        </div>

        <div class="login-box-body">
            <form action="auth/login" method="POST" id="login-form">
                <div class="form-group has-feedback">
                    <input name="username" type="text" class="form-control" placeholder="Username">
                    <span class="fa fa-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input name="password" type="password" class="form-control" placeholder="Password">
                    <span class="fa fa-lock form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-4 col-xs-push-8">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                </div>
            </form>
        </div>

        <div class="callout" style="display:none" id="message-callout">
            <h4 id="message-title"></h4>
            <p id="message-content"></p>
        </div>
    </div>

    <?= $this->fetch("_components/preloader.phtml"); ?>

    <script src="components/jquery/dist/jquery.min.js"></script>
    <script src="assets/js/login.js"></script>
    <script src="assets/js/preloader.js"></script>
</body>
</html>
